[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  CHROME_EXECUTABLE_PATH = "/usr/bin/chromium-browser"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer"]
