[build]
  publish = ".next"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 3000

[build.environment]
  NODE_VERSION = "20"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer", "chrome-aws-lambda"]
  directory = "netlify/functions"
